# Generated by Django 3.2.9 on 2022-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
